name: BedBattles
main: net.blockcade.Arcade.games.BedBattles.Main
description: Addition to GameCore
version: ${project.version}
api-version: 1.13
depend:
  - Arcade
commands:
  game:
    description: A command